FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install schedule

COPY . .

# Default command (can be overridden in compose)
# We use unbuffered output to see logs immediately
ENV PYTHONUNBUFFERED=1

CMD ["python", "daemon.py", "C07FMAQ3485"]
