#!/bin/bash

# Enhanced Mention Detection - Usage Examples
# This script shows common usage patterns for the enhanced mention detection feature

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║     Enhanced Mention Detection - Usage Examples               ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${BLUE}1. Check your Slack setup${NC}"
echo "   Verify your bot and user IDs are configured correctly"
echo ""
echo -e "${GREEN}   python3 check_slack_setup.py${NC}"
echo ""
echo "   Expected output:"
echo "   ✓ Bot User ID: U123456789"
echo "   ✓ Your User ID: U987654321"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo -e "${BLUE}2. Test the enhanced detection${NC}"
echo "   Run the test script to see what messages are detected"
echo ""
echo -e "${GREEN}   python3 test_enhanced_mentions.py${NC}"
echo ""
echo "   You'll be prompted for a channel ID to test"
echo "   The script will show:"
echo "   • Messages with bot mentions"
echo "   • Messages with keywords ('mohit', 'the real pm')"
echo "   • Messages with user mentions"
echo "   • Combined detection results"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo -e "${BLUE}3. Process mentions in a single channel${NC}"
echo "   Replace C08JF2UFCR1 with your actual channel ID"
echo ""
echo -e "${GREEN}   python3 main.py process-mentions --channels C08JF2UFCR1${NC}"
echo ""
echo "   This will:"
echo "   • Scan the channel for mentions and keywords"
echo "   • Show what messages were found"
echo "   • Analyze with AI and propose actions"
echo "   • Ask for your approval before executing"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo -e "${BLUE}4. Process mentions in multiple channels${NC}"
echo "   Replace with your actual channel IDs"
echo ""
echo -e "${GREEN}   python3 main.py process-mentions --channels C08JF2UFCR1 C08JF2UFCR2 C08JF2UFCR3${NC}"
echo ""
echo "   This will scan all specified channels and combine results"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo -e "${BLUE}5. Create test messages in Slack${NC}"
echo "   To test the detection, create these messages in a test channel:"
echo ""
echo "   ✅ Test 1: Direct bot mention"
echo -e "      ${YELLOW}@The Real PM schedule a meeting tomorrow at 2pm${NC}"
echo ""
echo "   ✅ Test 2: Keyword 'mohit'"
echo -e "      ${YELLOW}Hey mohit, can you review the PR?${NC}"
echo ""
echo "   ✅ Test 3: Phrase 'the real pm'"
echo -e "      ${YELLOW}Ask the real pm about the deployment${NC}"
echo ""
echo "   ✅ Test 4: User mention"
echo -e "      ${YELLOW}@Mohit what's the status?${NC}"
echo ""
echo "   ✅ Test 5: Multiple triggers"
echo -e "      ${YELLOW}@Mohit ask the real pm to remind me${NC}"
echo ""
echo "   ❌ Test 6: No triggers (should NOT be detected)"
echo -e "      ${YELLOW}The project is on track${NC}"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo -e "${BLUE}6. Understanding the approval process${NC}"
echo ""
echo "   After AI analysis, you'll see:"
echo ""
echo "   ════════════════════════════════════════════════════════════"
echo "   AGENT ANALYSIS"
echo "   ════════════════════════════════════════════════════════════"
echo "   [Human-readable analysis]"
echo "   [JSON action plan]"
echo "   ════════════════════════════════════════════════════════════"
echo ""
echo "   Approve and execute? [y/n/u to update]:"
echo ""
echo "   Options:"
echo "   • y - Execute all proposed actions"
echo "   • n - Cancel everything"
echo "   • u - Update mode (edit or delete individual actions)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo -e "${BLUE}7. Using update mode${NC}"
echo ""
echo "   If you choose 'u' for update mode, you can:"
echo ""
echo "   • delete 2    - Remove action #2"
echo "   • edit 1      - Modify action #1"
echo "   • done        - Finish editing and execute"
echo "   • cancel      - Abort everything"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo -e "${BLUE}8. Common troubleshooting${NC}"
echo ""
echo "   Problem: No messages found"
echo "   Solution: Make sure bot is in the channel"
echo -e "            ${GREEN}In Slack: /invite @The Real PM${NC}"
echo ""
echo "   Problem: Wrong user ID"
echo "   Solution: Check your .env file"
echo -e "            ${GREEN}python3 check_slack_setup.py${NC}"
echo ""
echo "   Problem: Bot not responding"
echo "   Solution: Verify bot permissions"
echo "            Required: channels:history, chat:write"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo -e "${BLUE}9. Quick reference${NC}"
echo ""
echo "   What gets detected:"
echo "   ✅ @The Real PM (bot mention)"
echo "   ✅ @Mohit (user mention)"
echo "   ✅ 'mohit' (keyword)"
echo "   ✅ 'the real pm' (phrase)"
echo ""
echo "   Security:"
echo "   • Only YOUR messages are processed for commands"
echo "   • Others get a polite refusal message"
echo "   • Bot's own messages are ignored"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo -e "${BLUE}10. Documentation${NC}"
echo ""
echo "   📚 Full guide:        ENHANCED_MENTIONS_GUIDE.md"
echo "   📋 Quick reference:   MENTIONS_QUICK_REF.md"
echo "   📊 Flow diagram:      MENTION_FLOW_DIAGRAM.md"
echo "   📝 Implementation:    ENHANCED_MENTIONS_SUMMARY.md"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "Ready to get started? Run one of the commands above!"
echo ""
